version: '3'

services:
  api-flask:
    build: ./flask/
    volumes:
      - ./flask/:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: polywine
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/logs:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080