name: project_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  http: ^1.2.1
  provider: ^6.1.2
  get: ^4.6.5
  permission_handler: ^11.3.0
  flutter_blue_plus: ^1.31.16


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/
  fonts:
    - family: RobotoRegular
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf

